services:
  proxy:
    image: traefik:v3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./certs:/etc/certs:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - accessible
networks:
  accessible:
    external: true
